### ISSUE TITLE
frame_center off by factor of two

### ISSUE THREAD

**Issue by sawellons** [agurvich/FIRE_studio#14]
See code below: gaspart is the particle dictionary

`      
        # Setting up 19 slices of width 5 kpc each, centered on 0
        depth = 5.
        ni = 19
        zstart = -(ni-1)/2.*depth

        # Loop over slices
        for iz in range(ni):

            # This was a test to make sure gaspart wasn't being modified each time - it's not.
            # Prints out the number of particles that should be in each slice
            nslices = []
            for iz2 in range(ni):
                nslices.append(np.sum((gaspart['Coordinates'][:,2] < zstart+iz2*depth+depth/2.)*(gaspart['Coordinates'][:,2] > zstart+iz2*depth-depth/2.)))
            print(nslices)
                
            gasStudio = GasStudio(
                datadir, snapnum,
                snapdir = simdir+'/output',
                gas_snapdict = gaspart,
                frame_half_width = imgsize,
                frame_half_thickness = depth/2.,
                frame_center = np.array([0,0,(zstart+iz*depth)/2.]),  # Note factor of 1/2 here
                scale_bar = False,
                sim_name = simname,
                loud = False)
`
The for loop which counts the number of particles in each slice gets the same number of particles as the gasStudio object, though ostensibly their centers differ by a factor of two.

**Comment by agurvich** [comment]
mike grudic just ran into what i think must be the same bug. i think i am accounting for the center twice somewhere. I don't have time right now to track it down but for future me:

inside the call to `computeFrameBoundaries` I compute xlim and ylim w.r.t uncentered frame which seems wrong. 

https://github.com/agurvich/FIRE_studio/blob/master/firestudio/studios/studio.py#L524

**Comment by agurvich** [comment]
Should no longer be an issue now that `firestudio.utils.camera_utils.Camera` objects are used instead of frame_half_width
